### ISSUE TITLE
"Add to cart" breaks with activated Plugin

### ISSUE THREAD

**Issue by mnaczenski** [FriendsOfShopware/FroshDevelopmentHelper#10]
The "add to cart" button breaks when the plugin is activated, because of a block inside the form.

![Bildschirmfoto 2020-03-27 um 14 20 52](https://user-images.githubusercontent.com/10058559/77760204-42d4ab00-7036-11ea-9e43-94055ee0205c.png)
![Bildschirmfoto 2020-03-27 um 14 21 26](https://user-images.githubusercontent.com/10058559/77760217-45370500-7036-11ea-96e0-f96194873b04.png)

**Comment by shyim** [comment]
Fixed with https://github.com/FriendsOfShopware/FroshDevelopmentHelper/commit/4e5da77f582a55d5a095efdcec651af656e5d399
