### ISSUE TITLE
Installation Problems

### ISSUE THREAD

**Issue by bibildibabeldibub** [FriendsOfShopware/FroshDevelopmentHelper#11]
Got problems with installation:

 Could not install plugin, got 2 failure(s).
  Required plugin/package "nikic/php-parser 4.3.0" is missing or not installed and activated
  Required plugin/package "friendsofphp/php-cs-fixer ^2.16" is missing or not installed and activated

**Comment by shyim** [comment]
You have to run in the plugin folder composer install

**Comment by bibildibabeldibub** [comment]
thats not working because i composer is not installed on my provider servers and i have no root access. 
Maybe i missing a point anywhere in the installation process?

**Comment by shyim** [comment]
You can download it from the shopware store as zip where all dependencies are included

**Comment by shyim** [comment]
Fixed with https://github.com/FriendsOfShopware/FroshDevelopmentHelper/commit/4d13fb498f850b05a49f2c77a8dc49d7a69b39bc
