### ISSUE TITLE
bin/console does not work when plugin is installed

### ISSUE THREAD

**Issue by zaifastafa** [FriendsOfShopware/FroshDevelopmentHelper#13]
Hi I am using the latest build of this repo from the git with Shopware 6.2.2. When executing `bin/console list` it gives me a huge error which seems like a vendor dependency related issue. Even after uninstalling the plugin the error stays unless I remove the vendor directories.

I do not have the error right now as I would have to setup the plugin again in the shop which I have already removed but I think it can be easily reproduced by
- installing the plugin
- installing vendor dependencies in the repo folder and inside the vendor directory
- executing `bin/console list` in the shop root

Thanks.

**Comment by shyim** [comment]
Did you run php vendor-builder.php ?

**Comment by zaifastafa** [comment]
No, I did a regular composer install in the repository root and then inside the vendor directory as well.

**Comment by shyim** [comment]
Remove the vendor folder and run php vendor-builder.php

**Comment by zaifastafa** [comment]
OK, I did tha, and now I get this error when clicking on installation from the backend
```
Plugin could not be installed due to error message "Could not install plugin, got 3 failure(s). Required plugin/package "nikic/php-parser 4.3.0" is missing or not installed and activated Required plugin/package "friendsofphp/php-cs-fixer ^2.16" is missing or not installed and activated Required plugin/package "psy/psysh ^0.10.4" is missing or not installed and activated"
```

**Comment by zaifastafa** [comment]
OK it worked after removing composer.lock file as well. Thanks for the support :+1:
