### ISSUE TITLE
Plugin sends development comments in the email template as well. 

### ISSUE THREAD

**Issue by zaifastafa** [FriendsOfShopware/FroshDevelopmentHelper#15]
When the plugin is installed, it sends the development comments in the template in also the email as seen here. This is the subject. And in the plain email view also you can see it. 

![image](https://user-images.githubusercontent.com/24492269/89985982-49865680-dc95-11ea-87a1-e029a0239ab7.png)

![image](https://user-images.githubusercontent.com/24492269/89986064-6de23300-dc95-11ea-9d4a-dff344f58b9d.png)

**Comment by shyim** [comment]
fixed with https://github.com/FriendsOfShopware/FroshDevelopmentHelper/commit/635b4b8303ce8135cbe57c67f0cc5ccc5f47978f
