### ISSUE TITLE
[Generation] Support for `JsonField`

### ISSUE THREAD

**Issue by aragon999** [FriendsOfShopware/FroshDevelopmentHelper#16]
Currently there seems to be a bug if a `JsonField` is used in the `frosh:make:definition` command:
```
[2020-09-19 12:35:31] console.ERROR: Error thrown while running command "frosh:make:definition '...'". 
Message: "Argument 1 passed to Symfony\Component\Console\Formatter\OutputFormatter::escapeTrailingBackslash() must be of the type string, array given, called in /srv/http/sw/development/vendor/symfony/console/Formatter/OutputFormatter.php on line 39"
```

The problem seems to be, that the default value of `propertyMapping` is an array:
https://github.com/shopware/platform/blob/master/src/Core/Framework/DataAbstractionLayer/Field/JsonField.php#L25
Which is responsible for the error generated here:
https://github.com/FriendsOfShopware/FroshDevelopmentHelper/blob/master/src/Component/Generator/QuestionHandler/GenericHandler.php#L71

While the basic fix would be, to use something like `json_encode` to display the field and prevent the error:
```php
-            $question = new Question('Parameter ' . $parameter->name, $default);
+            $defaultString = $default;
+            if (is_array($defaultString)) {
+                $defaultString = json_encode($default);
+            }
+            $question = new Question('Parameter ' . $parameter->name, $defaultString);
```

 I think this issue needs to be fixed on a deeper level, i.e. one probably wants to be able to specify the values for this field.

Therefore I think one needs to implement something like a `JsonFieldHandler`. If I find time, I think I can help with this as well.

**Comment by shyim** [comment]
fixed in last commit
