### ISSUE TITLE
Missing license warning when installing via composer

### ISSUE THREAD

**Issue by vardumper** [FriendsOfShopware/FroshDevelopmentHelper#21]
Why would there be a license check for a supposedly free plugin?

**Comment by shyim** [comment]
I assume you mean the Shopware License warning. I have marked it now as open source. Should be fixed then

**Comment by vardumper** [comment]
weirdly the shopworn license message did go away magically.

**Comment by shyim** [comment]
I have made the plugin in our backend as opensource. It will buy the license automaticly for you 😅
