### ISSUE TITLE
Plugin does not work after latest commit

### ISSUE THREAD

**Issue by zaifastafa** [FriendsOfShopware/FroshDevelopmentHelper#25]
Trying the 0.3 branch on shopware 6.4, it does not install anymore. 

Steps already tried: 
- installation after `git clone` through plugin manager (as mentioned in readme)
- installation after `composer install`
- installation after `composer2 install`

nothing works.

**Comment by shyim** [comment]
What does not work?

**Comment by zaifastafa** [comment]
Cannot be installed .. using 7.4 and shopware 6.4

**Comment by shyim** [comment]
Fixed with the latest master commit
