### ISSUE TITLE
The checkout summary layout is affected

### ISSUE THREAD

**Issue by zaifastafa** [FriendsOfShopware/FroshDevelopmentHelper#26]
When the plugin is activated, the summary box layout is messed up (if the customer comment box is not checked in cart setting) due to this line - 
`platform/src/Storefront/Resources/views/storefront/page/checkout/_page.html.twig:27`

It checks if the block is empty or not, but due to hidden twig comments it is not empty so it applies the `checkout-aside-no-offset` class. 

Expected: 
![image](https://user-images.githubusercontent.com/24492269/119268730-b14ad400-bc0d-11eb-894d-b61bbb1634f4.png)

How it is instead: 
![image](https://user-images.githubusercontent.com/24492269/119268801-fa9b2380-bc0d-11eb-845d-f265e2cdfcc1.png)

**Comment by shyim** [comment]
Can you look into source code and find the breaking block and add it here?
https://github.com/FriendsOfShopware/FroshDevelopmentHelper/blob/0.3/src/Component/Twig/NodeVisitor/BlogCommentNodeVisitor.php#L21

**Comment by zaifastafa** [comment]
Hey, yeah I know the block. Will create a PR :) thanks
