### ISSUE TITLE
Cannot create JsonField in make:definition

### ISSUE THREAD

**Issue by zaifastafa** [FriendsOfShopware/FroshDevelopmentHelper#32]
## Actual behaviour

When selecting `JsonField` it gives an error
`Argument 1 passed to Symfony\Component\Console\Formatter\OutputFormatter::escapeTrailingBackslash() must be of the type string, array given, called in /var/www/html/sw6/vendor/symfony/console/Formatter/OutputFormatter.php on line 47`  

## Expected behaviour

Can create JsonField like other fields

## Environment

Repository branch: 0.2
Shopware: 6.3.5.1

**Comment by shyim** [comment]
Fix with https://github.com/FriendsOfShopware/FroshDevelopmentHelper/commit/4ebeba99709fa459a382762b8848efdb5f14e1c7
