### ISSUE TITLE
Setting field as nullable works opposite of what is selected

### ISSUE THREAD

**Issue by zaifastafa** [FriendsOfShopware/FroshDevelopmentHelper#33]
## Actual behaviour

When creating make:definition and setting a property as nullable, it creates the reverse of what we select. 
For e.g a NOT NULL string is created as `/** @var string|null */` with the nullable setter and getters, and if a field is set as nullable, it creates it without the `null`.

## Expected behaviour

A nullable field should be created with a nullable indicator. 

## Environment

Branch: 0.2
Shopware: 6.3.5.1

**Comment by shyim** [comment]
I guess I was drunken
