### ISSUE TITLE
Installing 0.3.0-dev via Composer removes plenty of packages

### ISSUE THREAD

**Issue by amenk** [FriendsOfShopware/FroshDevelopmentHelper#34]
## Actual behaviour

    Installing the 0.3.0 branch via composer removes lots of packages and finally fails with

	> [ ! -f install.lock ] || bin/console system:update:finish
	PHP Fatal error:  Uncaught RuntimeException: You need to add "symfony/framework-bundle" as a Composer dependency. in /home/user/example/projects/example.de/bin/console:24
	Stack trace:
	#0 {main}
	  thrown in /home/user/example/projects/example.de/bin/console on line 24
	Script [ ! -f install.lock ] || bin/console system:update:finish handling the post-update-cmd event returned with error code 255

	Installation failed, reverting ./composer.json and ./composer.lock to their original content.

## Expected behaviour

    I can install and use the plugin, including the dev branch :-)

## Environment

    Please provide information about the environment in which the issue occurs (e.g. PHP version, webserver, Shopware version, debugging information if you can provide).

## Steps to reproduce

	composer2 require --dev --dry-run frosh/development-helper=0.3.x-dev
	./composer.json has been updated
	Running composer update frosh/development-helper --with-all-dependencies
	Loading composer repositories with package information
	Updating dependencies
	Lock file operations: 4 installs, 2 updates, 140 removals <-------

## Possible cause

https://github.com/FriendsOfShopware/FroshDevelopmentHelper/commit/4068e5455206faf052b45c851f5f92eac33f30e1 ?

**Comment by shyim** [comment]
Composer is always fuck up with plugins. Should be fixed with next release
