### ISSUE TITLE
Exception when sending an email

### ISSUE THREAD

**Issue by dsturm** [FriendsOfShopware/FroshDevelopmentHelper#37]
### PHP Version

8.0

### Shopware Version

6.4.3.1

### Actual behaviour

When sending a (test-)mail, it results in a critical Exception, because it adds an include comment node.

### Expected behaviour

The plugin should not add comments to mails, so sending an email should not trigger an exception.

### Steps to Reproduce?

- Install and activate 
- Send a test mail in backend

**Comment by shyim** [comment]
Can you test the commit here?

**Comment by dsturm** [comment]
Hej @shyim, thanks for the [commit](https://github.com/FriendsOfShopware/FroshDevelopmentHelper/commit/2be760e408ee23cf9297b543d39790a8bfb6ff8c). This fixed the issue!
