### ISSUE TITLE
Generate Code for Adding a Custom Field in a Plugin

### ISSUE THREAD

**Issue by amenk** [FriendsOfShopware/FroshDevelopmentHelper#40]
Currently we mostly create custom fields via admin panel. But to properly deploy a custom module, the field(s) should be created in code.

It would be nice if the frosh development helper could support creating such custom fields, like described in 

https://developer.shopware.com/docs/guides/plugins/plugins/framework/custom-field/add-custom-field#add-column-in-database-table

**Comment by shyim** [comment]
I would like to see this more in the JetBrains plugin, as the dev don't need to modify Shopware https://github.com/shopwareLabs/shopware6-phpstorm-plugin/issues/56

**Comment by amenk** [comment]
Totally agree
