### ISSUE TITLE
Feature Request: Overwrite Plugin Templates

### ISSUE THREAD

**Issue by amenk** [FriendsOfShopware/FroshDevelopmentHelper#41]
### Feature request

The twig generator does not seem to detect templates which were introduced in a plugin.

I would be nice if those are also supported.

~Question part: We are not even 100% sure if overriding such templates is possible in Shopware - if it isn't, this can be closed.
See also: https://stackoverflow.com/questions/69902189/override-twig-template-from-plugin~ (it is possible)

**Comment by shyim** [comment]
Do we still need this. The PhpStorm extension can do this already 🤔

**Comment by amenk** [comment]
It's fine if the extension does it, fits better there
