### ISSUE TITLE
Make BLACKLIST_KEYS configurable

### ISSUE THREAD

**Issue by RafaelKr** [FriendsOfShopware/FroshDevelopmentHelper#47]
### Please describe the feature you would like to see implemented.

We're using a plugin which uses Twig blocks for attributes. This leads to unrendered HTML.

![photo_2022-06-20_15-35-03](https://user-images.githubusercontent.com/14234815/174613512-394631dc-761f-43f7-93f2-d6f4c8586218.jpg)
![photo_2022-06-20_15-35-00](https://user-images.githubusercontent.com/14234815/174613451-5168830d-123b-4c14-b2b2-8d74d78abebb.jpg)

https://github.com/FriendsOfShopware/FroshDevelopmentHelper/blob/a630e2445730da5d5f7e666c413421dee15294d1/src/Component/Twig/NodeVisitor/BlogCommentNodeVisitor.php#L18-L25

It would be great if the BLACKLIST_KEYS could be configured via Symfony configuration.
https://symfony.com/doc/current/bundles/configuration.html

So any other Shopware app (plugin/theme) can add a `src/Resources/config/packages/frosh-development-helper.xml` with a config similiar to this:
```xml
<!-- src/Resources/config/packages/frosh-development-helper.xml -->
<?xml version="1.0" encoding="UTF-8" ?>
<container xmlns="http://symfony.com/schema/dic/services"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:frosh-development-helper="http://example.org/schema/dic/frosh_development_helper"
    xsi:schemaLocation="http://symfony.com/schema/dic/services
        https://symfony.com/schema/dic/services/services-1.0.xsd">

    <frosh-development-helper:config>
        <frosh-development-helper:blacklist-keys>
          <key>plugins_maxia_listing_variants_configurator_option_radio_label_attributes</key>
          <key>...</key>
        </frosh-development-helper:blacklist-keys>
    </frosh-development-helper:config>
</container>
```
And all the keys are merged with the default keys then.

BTW it would be great if a new version would be released to include the fix for #45

**Comment by amenk** [comment]
I see that it's a strpos for the blacklist ... so it might be enough to add some more items to the list (can we rename it also to something more speaking like SKIP_BLOCK_KEYWORDS ? 

So for the initially mentioned extension it might be fine to add "attributes" to the list.

For the Moorl-extensions it seems to be `element_moorl_merchant_finder_result_item_style` so `style` would be a good keyword.

I think it is easier to convince extensions vendors to use specific well-known keywords then adding such a symfony config just for the development helper.

What do you think?

**Comment by amenk** [comment]
https://github.com/FriendsOfShopware/FroshDevelopmentHelper/pull/49

**Comment by amenk** [comment]
@RafaelKr do you still need this or do you agree with a more generic skip list?

I would vote for close :-)

**Comment by RafaelKr** [comment]
Sorry for the late answer, I couldn't test it yet. But looking on the new/current implementation I think that works for now :) Although this approach has the downside that it can lead to false positives.

My current thought is that the most reliable implementation would be to walk down the Twig AST and determine for each node if it is inside an HTML tag or not. I had just 15 minutes to check if this possible and don't came to a final conclusion yet.
I think this is something outside the scope of this issue, still I would like to know what you think about this solution and if you maybe know if it's possible @shyim @amenk

**Comment by amenk** [comment]
Best solution would be if there would be [source maps, like we have for CSS and JavaScript, for HTML](https://stackoverflow.com/questions/16687707/is-there-sourcemaps-for-html) as well, but there still is no such a feature in browsers :-(

**Comment by RafaelKr** [comment]
I just found https://github.com/dimarick/twig-source-map-bundle and also tried it. It generates a sourcemap, but there's no way to read it in a browser. (Also the sourcemap is on file-level, not on block level, but that should be no problem to implement.)

![image](https://user-images.githubusercontent.com/14234815/195446851-e6438853-04b1-4fa6-b73c-2d2f88564754.png)

I just had a stupid idea which may work. I don't had a look at the exact format of a sourcemap, but thought maybe it's possible to inject the twig files as JavaScript files but commented out completely. This could work if sourcemaps support to place their "markers" also in comments.

**Comment by RafaelKr** [comment]
Awesome!
