### ISSUE TITLE
output indentation config

### ISSUE THREAD

**Issue by hlb-schmidt** [FriendsOfShopware/FroshDevelopmentHelper#5]
we use tabs for indenting our code, so would be nice if we could say `frosh:make:definition` (and everything else) to output code with tab indentation, instead of spaces.

and i guess some people want to change the 4 spaces to X spaces...

ps. for bonus points, read [.editorconfig](https://editorconfig.org/) (of the plugin) for indentation config.

**Comment by shyim** [comment]
In the underhood it useses php-cs-fixer. It could detect the plugin php_cs.dist and use it for formatting

**Comment by hlb-schmidt** [comment]
nice! works:

`.php_cs.dist` in the plugin (that we generate the files for) dir:
```
<?php
return PhpCsFixer\Config::create()->setIndent("\t");
```
