### ISSUE TITLE
Stopwatch error when trying to deactivate plugin

### ISSUE THREAD

**Issue by cscheibelhut** [FriendsOfShopware/FroshDevelopmentHelper#50]
### PHP Version

8.1

### Shopware Version

6.4

### Actual behaviour

```
[Symfony\Component\ErrorHandler\Error\FatalError]                                                              
  Compile Error: Cannot declare class Symfony\Component\Stopwatch\Stopwatch, because the name is already in use
```

### Expected behaviour

plugin deactivated

### Steps to Reproduce?

bin/console plugin:deactivate FroshDevelopmentHelper 

the error occurs in admin panel also

**Comment by amenk** [comment]
Does anyone have a clue how exactly this is caused and how it can be fixed?
It even seems to happen, when the plugin is added via composer but not installed & activated - during `php bin/console plugin:update` of other plugins. But actually I am not sure, if in that case the development helper is the culprit :-)

**Comment by amenk** [comment]
@shyim do you have an idea?

**Comment by shyim** [comment]
I will look into it 😅 . Need my Gitpod first https://github.com/FriendsOfShopware/FroshDevelopmentHelper/commit/7114b02de7c3afc24d669cd2fca71a7f9dd77041 😂

**Comment by shyim** [comment]
Problem 1
    - psy/psysh[v0.10.4, ..., v0.10.12] require symfony/var-dumper ~5.0|~4.0|~3.0|~2.7 -> found symfony/var-dumper[v2.7.0, ..., v2.8.52, v3.0.0, ..., v3.4.47, v4.0.0, ..., v4.4.47, v5.0.0, ..., v5.4.14] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires psy/psysh ^0.10.4 -> satisfiable by psy/psysh[v0.10.4, ..., v0.10.12].
    
    
The composer install is even not working 🤔

**Comment by amenk** [comment]
Awesome, thank you so much
