### ISSUE TITLE
Symfony Debug Bar not loading when FroshDevelopmentHelper active

### ISSUE THREAD

**Issue by btchp** [FriendsOfShopware/FroshDevelopmentHelper#60]
### PHP Version

8.1

### Shopware Version

6.5.2.1

### Actual behaviour

Symfony Debug Bar not loading when FroshDevelopmentHelper active. Just shows "loading" message and 404 error in browser JS console. If is deactivated the Symfony debug bar is working.

### Expected behaviour

Both working fine together.

### Steps to Reproduce?

install FroshDevelopmentHelper, activate, enable **dev** in ENV

**Comment by amenk** [comment]
@btchp Debug bare works here with 6.5.3.3, which plugin version did you try? Can you reproduce this on a recent, vanilla Shopware 6 version?

Which URL is causing the 404 error?

**Comment by shyim** [comment]
I cannot reproduce this also.
