### ISSUE TITLE
Plugin modifies Breadcrumb Object in Twig

### ISSUE THREAD

**Issue by jhit** [FriendsOfShopware/FroshDevelopmentHelper#61]
### PHP Version

8.1.21

### Shopware Version

6.4.20.2

### Actual behaviour

if I do `{{ dump(page.header.navigation.active.breadcrumb) }}` in Resources/views/storefront/layout/meta.html.twig I get different results depending on the plugin installed or not:

Plugin **not installed**:

```php
array:4 [▼
  0 => "Deutsch"
  1 => "Naturmode"
  2 => "Damen"
  3 => "Oberbekleidung Wolle"
]
```

Plugin **installed**

```php
array:4 [▼
  "50ea50da809248fab4b7f24c4c06ac95" => "Naturmode"
  "b1eec61ad3074f049aa9033728f066a5" => "Deutsch"
  "bc23106097554f22afb09ba68d5a13f7" => "Damen"
  "bca04995131242b58142ba6909c31892" => "Oberbekleidung Wolle"
]
```
Two things to note here:

1. The plugin messes up the order of the breadcrumb
2. the plugin changes the index type from `int` to `string / UUID`

this created quite a bit of headache for us because one developer was working with this plugin while another did not. And the Theme code worked on one system like expected and on the other one it messed up :-)

### Expected behaviour

The breadcrump object should be consistent with plugin installed.

### Steps to Reproduce?

Dump `page.header.navigation.active.breadcrumb` before installing plugin and then after plugin is active.

**Comment by shyim** [comment]
Cannot reproduce 🙈 
![image](https://github.com/FriendsOfShopware/FroshDevelopmentHelper/assets/6224096/a3e15c12-0844-4869-8791-9ddb42bb10f4)

I would tbh have also no idea, how the plugin could break this 🤔
