### ISSUE TITLE
Migration tables are created with utf8_unicode_ci while Shopware uses utf8mb4_unicode_ci

### ISSUE THREAD

**Issue by dianasalsa** [FriendsOfShopware/FroshDevelopmentHelper#64]
### PHP Version

8.1

### Shopware Version

6.5.7.3

### Plugin Version

1.0.2

### Actual behaviour

All tables created by frosh:make:migration have DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci`

Shopware tables all have DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci

Origin of the issue is doctrine itself, where utf8 is the fallback if nothing else is passed:
https://github.com/doctrine/dbal/blob/7c4aa971ca9e3195eed400ade4b3a00a2617671b/src/Platforms/AbstractMySQLPlatform.php#L564

So maybe just pass the correct charset as an option somewhere to fix this...

### Expected behaviour

Generated custom tables should match shopware tables

### Steps to Reproduce?

- Use frosh:make:definition to create a simple custom entity with a single column
- Add the definition to services.xml
- Use frosh:make:migration to generate the Migration

**Comment by shyim** [comment]
good catch. We should fix that too in the Shopware core 🤔 . This functionality will be also in the Core with 6.5.8.0 in January

**Comment by shyim** [comment]
```
./bin/console dal:migration:create
```

Use the core functionality, I think it makes no sense to maintain this functionality here anymore :)
